services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: esoliupo
      POSTGRES_PASSWORD: esoliupo
      POSTGRES_DB: esoliupo
    ports:
      - '5432:5432'
    volumes:
      - esoliupo_db_data:/var/lib/postgresql/data

volumes:
  esoliupo_db_data:
