export const ROLES = {
  SOCIO: 'SOCIO',
  COLABORADOR_EXTERNO: 'COLABORADOR_EXTERNO',
  JUNTA_DIRECTIVA: 'JUNTA_DIRECTIVA',
  ADMINISTRADOR: 'ADMINISTRADOR',
}

const ROLE_RANK = {
  [ROLES.SOCIO]: 1,
  [ROLES.COLABORADOR_EXTERNO]: 1,
  [ROLES.JUNTA_DIRECTIVA]: 2,
  [ROLES.ADMINISTRADOR]: 3,
}

export const PERMISSIONS = {
  MANAGE_USERS: ROLES.ADMINISTRADOR,
  MANAGE_ROLES: ROLES.ADMINISTRADOR,
  MANAGE_SITE_CONTENT: ROLES.ADMINISTRADOR,
  MANAGE_ANNOUNCEMENTS: ROLES.ADMINISTRADOR,
  SUPERADMIN: ROLES.ADMINISTRADOR,

  APPROVE_MEMBERS: ROLES.JUNTA_DIRECTIVA,
  MANAGE_EVENTS: ROLES.JUNTA_DIRECTIVA,
  MANAGE_TRAININGS: ROLES.JUNTA_DIRECTIVA,
  MANAGE_CONTACT: ROLES.JUNTA_DIRECTIVA,
}

export function isAtLeast(role, minRole) {
  return (ROLE_RANK[role] ?? 0) >= (ROLE_RANK[minRole] ?? Infinity)
}

export function hasPermission(role, permission) {
  const minRole = PERMISSIONS[permission]
  return minRole ? isAtLeast(role, minRole) : false
}
